### ISSUE TITLE
[!] Game breaking bug. Wandering troubadour "what advantage is there in seeking a wife" causes inescapable lockup

### ISSUE THREAD

**Issue by WHYDONTYOULIKETHEPIECEAPIE** [LilyModzStuff/warband_mod_source#61]
If you ask them that question, it zooms in on your characters face and says "click left mouse button to continue" but you are unable to continue and no button allows you to escape. you basically have to turn your computer off to get out.

**Comment by LilyModzStuff** [comment]
I will take a look at the dialogue to see if it is triggering a weird script or something.

**Comment by WHYDONTYOULIKETHEPIECEAPIE** [comment]
Okay thank you! :D

**Comment by LilyModzStuff** [comment]
I looked into it, appears to not be an issue on my end, might have just been the game having a memory overflow. Try patching the exe as 4gb.

**Comment by WHYDONTYOULIKETHEPIECEAPIE** [comment]
@LilyModzStuff 
> I looked into it, appears to not be an issue on my end, might have just been the game having a memory overflow. Try patching the exe as 4gb.

what do you mean "patch the exe as 4gb" ?

**Comment by LilyModzStuff** [comment]
@WHYDONTYOULIKETHEPIECEAPIE https://ntcore.com/?page_id=371
