### ISSUE TITLE
adult mod additions ideas request for future updates

### ISSUE THREAD

**Issue by WHYDONTYOULIKETHEPIECEAPIE** [LilyModzStuff/warband_mod_source#67]
Adult section of the mod ideas:

Arrows that cause enemies when hit to ragdoll and have a massive orgasm

Wizard spells that turn every enemy on the battlefield naked (reduced armor = easier to fight them!)

Wizard curse that makes all enemy horses force dismounting of their riders, turn around and fuck them in the ass with big horse dick

option to go to your personal stable and get fucked by big horse dick

sauna/steam room/ hot springs full of futas and exhibitionism humiliation type stuff with deep fisting content

stockades with naked prisoners

sexual torture dungeons with sex torture devices for traitors

Wizard spells that can turn female players into futanari herms

Wizard spells that can change the sex of any character to any other sex (already in the cheats menu but not as a wizard mechanic)

Wizard spells that can force all enemy horses to simultaneously orgasm and ragdoll causing half the enemy force to just crash into the floor and tumble in a massive wreck

Wizard spells that change all enemy arrows into dildos rendering them harmless unless you turn around and get hit in the back, in which case you ragdoll for 10 seconds from the massive orgasm of getting shot up the pussy

sword dildos. nuff said.

cum armor (just character wearing a heaping load of futa budder as armor)

Penis horses. That's right, DICKS YOU CAN RIDE. (no pun intended) the horse body is a giant dick, and the horses head is another dick, and each of the horses legs are dicks, and the horses hooves are ballsacks. instead of clippety clop the horses make a squishing sound when they run. when you run straight into an obstacle instead of your horse rearing up and freaking out your dick horse just cums everywhere because it RAMMED into something

Armored dick horses are just dick horses covered in condoms.

Charge stat name changed to FUCK or RAM

Human centaur horses (pictured right): http://www.worlddreambank.org/BIG/CLANGREE.JPG

Sexualized goods in the market. Butter changed to "Futa butter" Grain changed to "Masochism crunch cereal pain grain" cheese changed to "Futa chedder"

The ability to use kick or have kick used on you to kick or get kicked in the nuts, even if female results in "getting kicked in the grapes" and grapes and olives fall out of your pockets while you ragdoll and scream in pain.

during sex scenes if you're being raped the enemy will sometimes grab large bottle of wine and insert it into your ass to force you to butt chug the whole thing and get your character drunk for a day after escaping (blurry screen, slow unresponsive and delayed controls and touching anything makes you ragdoll for 5 seconds)

**Comment by LilyModzStuff** [comment]
Mod is supposed to be realistic with a serious tone. "stockades with naked prisoners" was originally planned but the guy who made the animations wouldn't give me permission.

**Comment by WHYDONTYOULIKETHEPIECEAPIE** [comment]
@LilyModzStuff 
Okay fair enough. Maybe in the distant long long future it could be added to "silly mode?" I'm greatful that you seem to like the other idea enough to not outright shut it down instantly, I suppose I have to say thank you for thinking about it because it may end up being a really cute and fun idea. all these ideas could be hidden off in their own special places too, not outright mixed into the whole game.
thanks and have a very good day :D
